# Generated by Django 3.2.9 on 2021-11-29 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dengji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gongdan', models.CharField(max_length=10)),
                ('lot', models.CharField(max_length=64)),
                ('event', models.CharField(max_length=256)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('unit', models.CharField(max_length=64)),
                ('op', models.CharField(max_length=64)),
            ],
        ),
    ]
