# Generated by Django 3.2.9 on 2021-11-29 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_dengji'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dengji',
        ),
    ]
