# Generated by Django 3.2.9 on 2021-12-01 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
