# Generated by Django 3.2.9 on 2021-12-01 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_alter_article_create_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='create_time',
            new_name='time',
        ),
    ]
