# Generated by Django 3.2.9 on 2021-12-01 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_alter_article_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
