# Generated by Django 3.2.9 on 2021-12-01 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_alter_article_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('score', models.FloatField(verbose_name='成绩')),
            ],
        ),
    ]
