# Generated by Django 3.2.9 on 2021-12-03 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
