# Generated by Django 3.2.9 on 2021-12-03 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0017_alter_test_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dengji',
        ),
    ]
