# Generated by Django 3.2.9 on 2021-12-03 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0020_alter_test_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='des',
            field=models.CharField(max_length=1024),
        ),
    ]
