# Generated by Django 3.2.9 on 2021-12-03 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0021_alter_test_des'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='or_list',
            field=models.CharField(max_length=128),
        ),
    ]
