# Generated by Django 3.2.9 on 2021-12-03 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0022_alter_test_or_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='client_name',
            field=models.CharField(max_length=128),
        ),
    ]
