# Generated by Django 3.2.9 on 2021-12-03 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0023_alter_test_client_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='des_confirm',
            field=models.CharField(max_length=1024),
        ),
    ]
