# Generated by Django 3.2.9 on 2021-12-03 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0024_alter_test_des_confirm'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
