# Generated by Django 3.2.9 on 2021-12-03 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0026_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='time',
            field=models.DateTimeField(default=True),
        ),
    ]
