# Generated by Django 3.2.9 on 2021-12-03 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0027_alter_test_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
