# Generated by Django 3.2.9 on 2021-12-08 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0031_alter_test_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='time',
            field=models.DateField(default=True),
        ),
    ]
