# Generated by Django 3.2.9 on 2021-12-09 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0033_alter_test_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='time',
            field=models.DateTimeField(default=False),
        ),
    ]
